<?php
/**
 * Privacy Web Counter — setup wizard.
 *
 * Visit this once after uploading the package. It writes config.php and
 * data/salt.php for you, and then DELETES ITSELF.
 *
 * Self-deletion is the point: this page has no password, and it is the one
 * thing on the site that chooses the visitor-hash salt. Left lying around, it
 * becomes live again the moment config.php goes missing — a botched FTP
 * overwrite, a rename, a tidy-up — and whoever loads it first picks the salt
 * for every visitor hash thereafter. Once setup is done there is nothing left
 * for it to do, so it goes.
 *
 * It refuses to run while config.php exists, which covers the gap if deletion
 * ever fails. To redo setup, re-upload this file from the repository.
 *
 * Every value from the form goes through var_export() or an explicit (int)
 * cast before it's written into config.php, never raw string concatenation —
 * config.php is executable PHP, so anything less would let a submitted value
 * break out of the generated file and run as code.
 */

$configPath = __DIR__ . '/config.php';

function h($s) { return htmlspecialchars((string) $s, ENT_QUOTES, 'UTF-8'); }

if (file_exists($configPath)) {
    ?><!doctype html><meta charset="utf-8"><title>Already configured</title>
    <body style="font:16px system-ui;padding:2rem;max-width:36rem;margin:0 auto;line-height:1.5">
    <h1>Already configured</h1>
    <p><code>config.php</code> already exists, so this installer won't touch it.
    Open <a href="index.php">index.php</a> for your dashboard, or edit
    <code>config.php</code> directly to change settings.</p>
    <p>To redo setup from scratch, delete <code>config.php</code> and reload this page.</p>
    </body><?php
    exit;
}

$isPost = isset($_SERVER['REQUEST_METHOD']) && $_SERVER['REQUEST_METHOD'] === 'POST';
$errors = [];
$saved  = false;
$writeError = null;
$generatedPhp = null;
$generatedSalt = null;
$selfDeleted = false;

$str = function ($key, $default = '') {
    return isset($_POST[$key]) ? trim((string) $_POST[$key]) : $default;
};

$siteName     = $isPost ? $str('site_name') : '';
$timezone     = $isPost ? $str('timezone', 'UTC') : 'UTC';
$ownHosts     = $isPost ? $str('own_hosts') : '';
$excludeIps   = $isPost ? $str('exclude_ips') : '';
$retention    = $isPost ? $str('retention_days', '0') : '0';
$backupDays   = $isPost ? $str('backup_days', '14') : '14';
$liveInterval = $isPost ? $str('live_interval', '15') : '15';
$recentLogLimit = $isPost ? $str('recent_log_limit', '50') : '50';
$liveFeedLimit  = $isPost ? $str('live_feed_limit', '10') : '10';
$salt         = $isPost ? $str('salt') : bin2hex(random_bytes(24));

$recordBots     = $isPost ? !empty($_POST['record_bots'])     : true;
$jsBeacon       = $isPost ? !empty($_POST['js_beacon'])       : true;
$countDashboard = $isPost ? !empty($_POST['count_dashboard']) : true;
// The two per-visitor displays default OFF. Aggregate totals are harmless on a
// public dashboard; a row-by-row trace of what one person read, with their
// browser, OS, device and country beside it, is not. Opt in deliberately.
$liveFeed       = $isPost ? !empty($_POST['live_feed'])       : false;
$showRecentLog  = $isPost ? !empty($_POST['show_recent_log']) : false;
$showCampaigns  = $isPost ? !empty($_POST['show_campaigns'])  : true;
$poweredBy      = $isPost ? !empty($_POST['powered_by'])      : true;
$showGithub     = $isPost ? !empty($_POST['show_github'])     : true;

if ($isPost) {
    if ($siteName === '') {
        $errors[] = 'Site name is required.';
    }
    if (!in_array($timezone, DateTimeZone::listIdentifiers(), true)) {
        $errors[] = 'That timezone is not recognized.';
    }
    if ($salt === '' || strlen($salt) < 16) {
        $errors[] = 'Salt is missing or too short — reload the page to get a fresh one.';
    }
    if (!ctype_digit($retention)) {
        $errors[] = 'Retention days must be a whole number.';
    }
    if (!ctype_digit($backupDays)) {
        $errors[] = 'Backup days must be a whole number.';
    }
    if (!ctype_digit($liveInterval)) {
        $errors[] = 'Live interval must be a whole number.';
    }
    if (!ctype_digit($recentLogLimit) || (int) $recentLogLimit < 1) {
        $errors[] = 'Recent visitors row count must be a whole number of 1 or more.';
    }
    if (!ctype_digit($liveFeedLimit) || (int) $liveFeedLimit < 1) {
        $errors[] = 'Live feed row count must be a whole number of 1 or more.';
    }

    $ownHostsArr = array_values(array_filter(array_map('trim', explode(',', $ownHosts))));
    $excludeIpsArr = array_values(array_filter(
        array_map('trim', preg_split('/\r?\n/', $excludeIps)),
        function ($ip) { return $ip !== '' && filter_var($ip, FILTER_VALIDATE_IP); }
    ));

    if (!$errors) {
        $lines = [];
        $lines[] = '<?php';
        $lines[] = '/**';
        $lines[] = ' * Privacy Web Counter — configuration';
        $lines[] = ' * Generated by install.php on ' . date('Y-m-d H:i:s') . '.';
        $lines[] = ' * Edit this file directly any time — install.php will not touch it again.';
        $lines[] = ' */';
        $lines[] = '';
        $lines[] = 'return [';
        $lines[] = "    'db_path' => __DIR__ . '/data/stats.db',";
        $lines[] = "    'timezone' => " . var_export($timezone, true) . ',';
        $lines[] = '';
        $lines[] = '    // The visitor-hash salt is NOT here — it lives in data/salt.php, which is';
        $lines[] = '    // blocked from the web. Do not move it back into this file.';
        $lines[] = '';
        $lines[] = '    // Addresses of proxies allowed to set X-Forwarded-For / X-Real-IP /';
        $lines[] = '    // CF-Connecting-IP. Leave empty unless a CDN really sits in front of';
        $lines[] = '    // this site: any address listed here can claim to be any visitor.';
        $lines[] = "    'trusted_proxies' => [],";
        $lines[] = '';
        $lines[] = "    'exclude_paths' => " . var_export(['/robots.txt', '/favicon.ico', '/sitemap.xml'], true) . ',';
        $lines[] = "    'exclude_ips' => " . var_export($excludeIpsArr, true) . ',';
        $lines[] = "    'record_bots' => " . var_export($recordBots, true) . ',';
        $lines[] = "    'retention_days' => " . (int) $retention . ',';
        $lines[] = "    'backup_days' => " . (int) $backupDays . ',';
        $lines[] = "    'js_beacon' => " . var_export($jsBeacon, true) . ',';
        $lines[] = "    'site_name' => " . var_export($siteName, true) . ',';
        $lines[] = "    'count_dashboard' => " . var_export($countDashboard, true) . ',';
        $lines[] = "    'live_interval' => " . (int) $liveInterval . ',';
        $lines[] = "    'live_feed' => " . var_export($liveFeed, true) . ',';
        $lines[] = "    'show_recent_log' => " . var_export($showRecentLog, true) . ',';
        $lines[] = "    'recent_log_limit' => " . (int) $recentLogLimit . ',';
        $lines[] = "    'live_feed_limit' => " . (int) $liveFeedLimit . ',';
        $lines[] = "    'show_campaigns' => " . var_export($showCampaigns, true) . ',';
        $lines[] = "    'own_hosts' => " . var_export($ownHostsArr, true) . ',';
        $lines[] = "    'powered_by' => " . var_export($poweredBy, true) . ',';
        $lines[] = "    'show_github' => " . var_export($showGithub, true) . ',';
        $lines[] = '];';
        $lines[] = '';
        $generatedPhp = implode("\n", $lines);

        $generatedSalt = "<?php\n"
            . "/**\n"
            . " * Visitor-hash salt — the secret behind every 'visitor' value in the database.\n"
            . " *\n"
            . " * It lives in data/ because data/.htaccess blocks this folder from the web.\n"
            . " * Anyone who obtains this string can hash the entire IPv4 address space in\n"
            . " * minutes and turn every stored visitor hash back into a real IP address.\n"
            . " * Never commit it, never paste it anywhere, and back it up alongside the\n"
            . " * database — losing it resets unique-visitor counting.\n"
            . " */\n"
            . "\n"
            . 'return ' . var_export($salt, true) . ";\n";

        $dataDir = __DIR__ . '/data';
        if (!is_dir($dataDir)) {
            @mkdir($dataDir, 0755, true);
        }

        // Salt first: config.php existing is what locks this installer, so it must
        // not appear until the salt beside it is safely on disk.
        $saltOk = @file_put_contents($dataDir . '/salt.php', $generatedSalt, LOCK_EX) !== false;

        if (!$saltOk) {
            $writeError = 'Could not write data/salt.php — that folder is not writable by PHP.';
        } elseif (@file_put_contents($configPath, $generatedPhp, LOCK_EX) === false) {
            $writeError = 'Could not write config.php — this folder is not writable by PHP.';
        } else {
            $saved = true;

            // Nothing left for this file to do, and leaving it is a standing risk —
            // see the note at the top. Writing config.php just proved PHP can create
            // files in this directory, which is the same permission unlink needs, so
            // this almost always succeeds. If it doesn't, the success page says so.
            $selfDeleted = @unlink(__FILE__);
        }
    }
}

$tzList = DateTimeZone::listIdentifiers();
?><!doctype html>
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex">
<title>Set up — Privacy Web Counter</title>
<script>
try {
  var w3bTheme = localStorage.getItem('w3b_theme');
  if (w3bTheme === 'light' || w3bTheme === 'dark') document.documentElement.setAttribute('data-theme', w3bTheme);
} catch (e) {}
</script>
<style>
:root{
  --bg:#ffffff; --ink:#16181d; --dim:#6b7280; --line:#e4e5e9;
  --accent:#2563eb; --accent-soft:#dbe6ff; --err:#dc2626; --ok:#16a34a;
}
@media (prefers-color-scheme:dark){
  :root:not([data-theme="light"]){
    --bg:#000000; --ink:#e8eaee; --dim:#9099a6; --line:#26262b;
    --accent:#1d4ed8; --accent-soft:#101b3d; --err:#b91c1c;
  }
}
:root[data-theme="dark"]{
  --bg:#000000; --ink:#e8eaee; --dim:#9099a6; --line:#26262b;
  --accent:#1d4ed8; --accent-soft:#101b3d; --err:#b91c1c;
}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
  font:15px/1.5 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
.wrap{max-width:640px;margin:0 auto;padding:2rem 1rem 4rem}
h1{font-size:1.4rem;margin:0 0 .25rem}
.sub{color:var(--dim);font-size:.88rem;margin:0 0 1.5rem}
.topbar{display:flex;align-items:center;gap:1rem;margin-bottom:1rem}
.theme-toggle{background:transparent;color:var(--dim);border:1px solid var(--line);border-radius:0;
  padding:.3rem .6rem;font:inherit;font-size:.75rem;cursor:pointer;white-space:nowrap;margin-left:auto}
.theme-toggle:hover{color:var(--ink);border-color:var(--accent)}
.section{margin-bottom:2rem}
.section h2{font-size:.8rem;letter-spacing:.09em;text-transform:uppercase;color:var(--dim);margin:0 0 1rem}
label{display:block;font-size:.85rem;font-weight:600;margin:0 0 .3rem}
.help{color:var(--dim);font-size:.78rem;margin:.3rem 0 0}
input[type=text],input[type=number],select,textarea{
  width:100%;padding:.5rem .6rem;border:1px solid var(--line);border-radius:6px;
  background:var(--bg);color:var(--ink);font:inherit;margin-bottom:1rem}
textarea{min-height:4.5rem;resize:vertical}
.field{margin-bottom:1rem}
.field:last-child{margin-bottom:0}
.check{display:flex;align-items:flex-start;gap:.5rem;margin-bottom:.9rem}
.check:last-child{margin-bottom:0}
.check input{margin-top:.25rem;accent-color:var(--accent)}
.check label{margin:0;font-weight:600}
.check .help{margin-top:.15rem}
button[type=submit]{background:var(--accent);color:#fff;border:0;border-radius:0;padding:.4rem .8rem;
  font:inherit;font-size:.82rem;font-weight:650;cursor:pointer}
.errors{background:color-mix(in srgb, var(--err) 10%, transparent);border-radius:8px;
  padding:.9rem 1.1rem;margin-bottom:1.5rem;color:var(--err);font-size:.88rem}
.errors ul{margin:.3rem 0 0;padding-left:1.2rem}
.success h1{color:var(--ok)}
code{background:var(--accent-soft);padding:.1rem .35rem;border-radius:4px;font-size:.9em}
textarea.code{font-family:ui-monospace,Consolas,monospace;font-size:.8rem;min-height:16rem}
.next{padding-left:1.2rem}
.next li{margin-bottom:.5rem}
a{color:var(--accent)}
</style>
<div class="wrap">

  <div class="topbar">
    <button type="button" id="theme-toggle" class="theme-toggle">Dark mode</button>
  </div>

<?php if ($saved): ?>

  <div class="section success">
    <h1>Setup complete</h1>
    <p>Written: <code>config.php</code> for your settings, and <code>data/salt.php</code>
    for the visitor-hash salt. Keep <code>data/salt.php</code> secret and back it up with
    your database — losing it resets unique-visitor counting.</p>
    <?php if ($selfDeleted): ?>
      <p><code>install.php</code> has deleted itself. It had no password and it chooses
      the salt, so leaving it in place would mean anyone could re-run setup if
      <code>config.php</code> ever went missing. Re-upload it from the repository if you
      need to redo setup.</p>
    <?php else: ?>
      <div class="errors">
        <strong>Delete <code>install.php</code> yourself now, over FTP.</strong>
        <p style="margin:.6rem 0 0">It could not remove itself. Until it is gone, anyone
        who reaches this URL can re-run setup and choose your visitor-hash salt if
        <code>config.php</code> is ever deleted or renamed.</p>
      </div>
    <?php endif; ?>
  </div>
  <div class="section">
    <h2>Next steps</h2>
    <ol class="next">
      <li>Make sure <code>data/</code> is writable by PHP — <code>755</code> normally.
        If hits still aren't recording, ask your host which owner PHP runs as rather
        than setting <code>777</code>, which on shared hosting grants write access to
        every other account on the server.</li>
      <li>Make sure your pages are <code>.php</code> files, not <code>.html</code>.
        Rename them if needed — <code>.php</code> files already run PHP, no extra
        handler directives required. See the README for redirect rules that keep
        old <code>.html</code> URLs working.</li>
      <li>Add this line to the very top of every page you want counted — before
        <code>&lt;!doctype html&gt;</code>, nothing in front of it, not even a space:
        <br><code>&lt;?php require_once $_SERVER['DOCUMENT_ROOT'] . '/YOUR-FOLDER-NAME/counter.php'; ?&gt;</code></li>
      <li>Visit a counted page, then open <a href="index.php">index.php</a> for your dashboard.</li>
    </ol>
  </div>

<?php else: ?>

  <h1>Set up Privacy Web Counter</h1>
  <p class="sub">A self-hosted, first-party traffic counter — no cookies, no third-party domain, no IP
  addresses stored. Source on <a href="https://github.com/RobBobbins/privacy-web-counter">GitHub</a>.</p>
  <p class="sub">This writes <code>config.php</code> and <code>data/salt.php</code> for you,
  then deletes itself. Nothing is tracked until you finish this.</p>
  <p class="sub">This page handles configuration only. After it runs you still need to make sure
  your pages are <code>.php</code> files and add one line to each page you want counted.
  Both steps are explained after setup finishes.</p>

  <?php if ($writeError): ?>
    <div class="errors">
      <strong><?= h($writeError) ?></strong>
      <p style="margin:.6rem 0 0">Create both files yourself instead. First
      <code>data/salt.php</code> — keep this one secret, it must never be readable
      from the web:</p>
      <textarea class="code" readonly onclick="this.select()"><?= h($generatedSalt) ?></textarea>
      <p style="margin:.6rem 0 0">Then <code>config.php</code>, in this same folder:</p>
      <textarea class="code" readonly onclick="this.select()"><?= h($generatedPhp) ?></textarea>
      <p style="margin:.6rem 0 0">Delete <code>install.php</code> over FTP once both exist.</p>
    </div>
  <?php endif; ?>

  <?php if ($errors): ?>
    <div class="errors">
      <strong>Fix these and try again:</strong>
      <ul><?php foreach ($errors as $e): ?><li><?= h($e) ?></li><?php endforeach; ?></ul>
    </div>
  <?php endif; ?>

  <form method="post">
    <div class="section">
      <h2>Basics</h2>
      <div class="field">
        <label for="site_name">Site name</label>
        <input type="text" id="site_name" name="site_name" value="<?= h($siteName) ?>" placeholder="My Site" required>
        <p class="help">Shown as the dashboard's title.</p>
      </div>
      <div class="field">
        <label for="timezone">Timezone</label>
        <select id="timezone" name="timezone">
          <?php foreach ($tzList as $tz): ?>
            <option value="<?= h($tz) ?>"<?= $tz === $timezone ? ' selected' : '' ?>><?= h($tz) ?></option>
          <?php endforeach; ?>
        </select>
        <p class="help">Days and hours on the dashboard use this.</p>
      </div>
      <div class="field">
        <label for="own_hosts">Your own hostnames</label>
        <input type="text" id="own_hosts" name="own_hosts" value="<?= h($ownHosts) ?>" placeholder="example.com, www.example.com">
        <p class="help">Comma-separated. Put your actual domain here —
        <code>yourdomain.com</code> and <code>www.yourdomain.com</code>. Without this, every
        click between your own pages shows up as a referrer instead of internal navigation.</p>
      </div>
      <div class="field">
        <label for="salt">Visitor-hash salt</label>
        <input type="text" id="salt" name="salt" value="<?= h($salt) ?>">
        <p class="help">Auto-generated — leave as is. This is the secret behind every visitor
        hash in the database. The stored hashes are only irreversible while this string stays
        secret: anyone who obtains it can turn every hash back into an IP address. Saved to
        <code>data/salt.php</code> (blocked from the web), never to <code>config.php</code>.
        Set once; changing it resets unique-visitor counting.</p>
      </div>
    </div>

    <div class="section">
      <h2>Privacy &amp; retention</h2>
      <div class="check">
        <input type="checkbox" id="record_bots" name="record_bots" value="1"<?= $recordBots ? ' checked' : '' ?>>
        <div><label for="record_bots">Record bot / crawler hits</label>
        <p class="help">Stored separately and hidden from the dashboard by default. Costs nothing to leave on.</p></div>
      </div>
      <div class="field">
        <label for="retention_days">Delete hits older than (days)</label>
        <input type="number" id="retention_days" name="retention_days" min="0" value="<?= h($retention) ?>">
        <p class="help">0 keeps everything forever.</p>
      </div>
      <div class="field">
        <label for="backup_days">Keep daily database backups for (days)</label>
        <input type="number" id="backup_days" name="backup_days" min="0" value="<?= h($backupDays) ?>">
        <p class="help">0 turns automatic backups off entirely.</p>
      </div>
      <div class="field">
        <label for="exclude_ips">Never count these IP addresses</label>
        <textarea id="exclude_ips" name="exclude_ips" placeholder="203.0.113.45"><?= h($excludeIps) ?></textarea>
        <p class="help">One per line. Add your own so your visits don't inflate the numbers — find it at ifconfig.me.</p>
      </div>
    </div>

    <div class="section">
      <h2>JavaScript</h2>
      <div class="check">
        <input type="checkbox" id="js_beacon" name="js_beacon" value="1"<?= $jsBeacon ? ' checked' : '' ?>>
        <div><label for="js_beacon">Enable referrer-recovery beacon</label>
        <p class="help">Adds one small inline script to every counted page, so referrers the
        Referer header loses can still be recovered. Turn off for a tracker with zero
        JavaScript — core tracking, UTM capture and backups all keep working either way.</p></div>
      </div>
    </div>

    <div class="section">
      <h2>Dashboard display</h2>
      <p class="help" style="margin-bottom:1rem">Your dashboard has no password — anyone who
      finds the folder can read your traffic numbers. It carries <code>noindex</code> so search
      engines skip it, but that is a request, not a lock. If that concerns you, put it behind
      HTTP basic auth via <code>.htaccess</code> after setup, or choose an unguessable folder
      name.</p>
      <div class="check">
        <input type="checkbox" id="count_dashboard" name="count_dashboard" value="1"<?= $countDashboard ? ' checked' : '' ?>>
        <div><label for="count_dashboard">Count visits to the dashboard itself</label>
        <p class="help">If off, the dashboard stays out of its own stats.</p></div>
      </div>
      <div class="field">
        <label for="live_interval">Live-update interval (seconds)</label>
        <input type="number" id="live_interval" name="live_interval" min="0" value="<?= h($liveInterval) ?>">
        <p class="help">0 turns live updating off and goes back to a plain static page.</p>
      </div>
      <div class="check">
        <input type="checkbox" id="live_feed" name="live_feed" value="1"<?= $liveFeed ? ' checked' : '' ?>>
        <div><label for="live_feed">Show the "Happening now" live feed</label>
        <p class="help">Off by default. Your dashboard is public, so this feed is too — no
        identities exposed, but anyone watching sees which pages are being read within seconds.</p></div>
      </div>
      <div class="field">
        <label for="live_feed_limit">Live feed rows</label>
        <input type="number" id="live_feed_limit" name="live_feed_limit" min="1" value="<?= h($liveFeedLimit) ?>">
        <p class="help">How many recent hits the "Happening now" feed shows at once.</p>
      </div>
      <div class="check">
        <input type="checkbox" id="show_recent_log" name="show_recent_log" value="1"<?= $showRecentLog ? ' checked' : '' ?>>
        <div><label for="show_recent_log">Show the detailed "Recent visitors" table</label>
        <p class="help">Off by default, and the most revealing thing here. One row per hit with
        browser, OS, device and referrer — on a quiet site that is a readable trace of what a
        single person browsed, in public.</p></div>
      </div>
      <div class="field">
        <label for="recent_log_limit">Recent visitors rows</label>
        <input type="number" id="recent_log_limit" name="recent_log_limit" min="1" value="<?= h($recentLogLimit) ?>">
        <p class="help">How many hits the "Recent visitors" table shows.</p>
      </div>
      <div class="check">
        <input type="checkbox" id="show_campaigns" name="show_campaigns" value="1"<?= $showCampaigns ? ' checked' : '' ?>>
        <div><label for="show_campaigns">Show the "Campaign sources" table</label>
        <p class="help">Only appears once a hit carries a utm_source parameter. Harmless to leave on if you don't use UTM links.</p></div>
      </div>
      <div class="check">
        <input type="checkbox" id="powered_by" name="powered_by" value="1"<?= $poweredBy ? ' checked' : '' ?>>
        <div><label for="powered_by">Show "LISTEN TO: PGNIP.ca comedy podcast" credit</label>
        <p class="help">Entirely optional — no strings attached either way.</p></div>
      </div>
      <div class="check">
        <input type="checkbox" id="show_github" name="show_github" value="1"<?= $showGithub ? ' checked' : '' ?>>
        <div><label for="show_github">Show a link to this project's GitHub repo</label>
        <p class="help">Appears at the bottom of the dashboard footer.</p></div>
      </div>
    </div>

    <button type="submit">Write config.php</button>
  </form>

<?php endif; ?>

</div>

<script>
(function () {
  var root = document.documentElement;
  var btn  = document.getElementById('theme-toggle');
  if (!btn) return;

  function current() {
    var explicit = root.getAttribute('data-theme');
    if (explicit) return explicit;
    return matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
  }
  function label(theme) {
    btn.textContent = theme === 'dark' ? 'Light mode' : 'Dark mode';
  }

  label(current());
  btn.addEventListener('click', function () {
    var next = current() === 'dark' ? 'light' : 'dark';
    root.setAttribute('data-theme', next);
    try { localStorage.setItem('w3b_theme', next); } catch (e) {}
    label(next);
  });
})();
</script>
</html>
